// frontend/src/App.vue
<template lang="pug">
t-app
  t-container
    transition(name="t-fade")
      router-view
  t-drawer
    router-link(to="/")
      t-icon-text(icon="space_dashboard", outlined) Dashboard
    router-link(to="/users")
      t-icon-text(icon="people" outlined) Users
    router-link(to="/about")
      t-icon-text(icon="info", outlined) About
  t-nav
    span Chit Managemnet System
    a(href="/api/logout") Logout
  t-confirm
</template>
<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({});
</script>

// frontend/src/App.svelte
<script lang="ts">
	import {Link, Router} from 'svelte-routing';
	import {Container, Drawer, IconText, Nav, Confirm} from '@theme/';
	import Routes from './routes/index.svelte';
	let basepath = '/';
</script>
<template lang="pug">
#app
	Router({basepath})
		Container
			Routes
		Drawer
			Link(to="/")
				IconText(icon="space_dashboard", outlined) Dashboard
			Link(to="/users")
				IconText(icon="people" outlined) Users
			Link(to="/about")
				IconText(icon="info", outlined) About
		Nav
			span Chit Managemnet System
			a(href="/api/logout") Logout
		Confirm
</template>
